name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-lates, ubuntu-24.04-arm]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: run tests
      run: |
        cd tests
        make
        bin/tests
    - name: compile examples
      run: |
        cd examples
        make
