name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: install capstone
      run: brew install capstone
    - name: run tests
      run: |
        cd tests
        make
        bin/tests
    - name: compile examples
      run: |
        cd examples
        make
  linux:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: compile tests
      run: |
        cd tests
        make
    - name: compile examples
      run: |
        cd examples
        make
